### PR TITLE
Bump snappy-java version to support Apple silicon

### PR DESCRIPTION
**Pull request by zac1st1k**
To fix issue
https://github.com/clj-commons/byte-transforms/issues/8

bum snappy-java to a compatible version
https://github.com/xerial/snappy-java/releases/tag/1.1.8.2

### CODE REVIEW

**Comment by KingMob** [comment]
@zac1st1k Thanks for this PR. 

I can't personally verify it, since I don't have an ARM mac. Maybe @slipset knows how to set up CircleCI to test on Apple silicon, but I don't want to hold you up, so I'm approving.

**Comment by KingMob** [comment]
Fixes #8

**Comment by KingMob** [comment]
Hey @zac1st1k , I was going to credit you in the new changelog. How would you like to be listed? Github username, just Zac, Zac Lastname (I'll need your last name), or something else?

If it's faster, I can be reached at kingmob on the Clojurians slack.

**Comment by KingMob** [comment]
I found your last name from your email, it's Xu, correct?

**Comment by zac1st1k** [comment]
Hey @KingMob , yes, it's Xu! Thanks a lot!

I have verified the PR as screenshot shows below.

image

**Pull request merged**
